---
deployment:
  tasks:
    - export DEPLOYPATH=/home/pinkettu/testgit/
    - /bin/cp -r css $DEPLOYPATH/css
    - /bin/cp -r images $DEPLOYPATH/images
    - /bin/cp -r fonts $DEPLOYPATH/fonts
    - /bin/cp -r custom $DEPLOYPATH/custom
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp explore.html $DEPLOYPATH
    - /bin/cp profile.html $DEPLOYPATH
    - /bin/cp pinks.html $DEPLOYPATH
    - /bin/cp login.html $DEPLOYPATH
    - /bin/cp signup.html $DEPLOYPATH